spring:
  application:
    name: finova-backend-file-service
  # ?? dev ??
  profiles:
    active: dev
  #  # ?? swagger3
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  #  # session ??
  #  session:
  #    store-type: redis
  #    # 30 ???
  #    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finova
    username: root
    password: root
#  # Redis ??
#  redis:
#    host: localhost # todo ???
#    port: 6379
#    password: 123321
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 1
#        time-between-eviction-runs: 10s
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/file
#    # cookie 30 ???
#    session:
#      cookie:
#        max-age: 2592000
#        path: /api
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # ????????????
#      logic-delete-value: 1 # ?????????? 1?
#      logic-not-delete-value: 0 # ?????????? 0?
#knife4j:
#  enable: true


finova:
#  jwt:
#    # ??jwt??????????
#    admin-secret-key: itcast
#    # ??jwt????
#    admin-ttl: 7200000
#    # ?????????????
#    admin-token-name: token
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.finova.**.domain.model
  configuration:
    #??????
    map-underscore-to-camel-case: true
