finova:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: finova
    username: root
    password: root
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tJMP71xv3KtwuTc9VMn
    access-key-secret: YyAUrc8KWhvFeThnN9TkBifuSrXCjs
    bucket-name: node-picture