spring:
  application:
    name: finova-backend-user-service
  # ?? dev ??
  profiles:
    active: default
#  # ?? swagger3
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  # session ??
#  session:
#    store-type: redis
#    # 30 ???
#    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finova
    username: root
    password: root
  # Redis ??
  redis:
    host: 112.74.176.236 # todo ???
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
#    # cookie 30 ???
#    session:
#      cookie:
#        max-age: 2592000
#        path: /api
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # ????????????
#      logic-delete-value: 1 # ?????????? 1?
#      logic-not-delete-value: 0 # ?????????? 0?

# 自定义Jwt认证服务
jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

knife4j:
  enable: true
  openapi:
    title: 用户服务接口文档
    description: 用户服务接口文档
    # aaa"
    email: 2484315823@qq.com
    concat: lys
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 接口文档
        api-rule: package
        api-rule-resources:
          - com.finova.finovabackenduserservice.controller
